// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDHPtiunUAM9fFjakFN_BnRxNboNgR18',
    appId: '1:570543922512:android:e767cf7572a8f7fb176055',
    messagingSenderId: '570543922512',
    projectId: 'kostparkir',
    databaseURL:
        'https://kostparkir-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kostparkir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM14PiktAwfd7ZwOlPZR8O4GNrLHDFiIY',
    appId: '1:570543922512:ios:8d051be3bb7b2a82176055',
    messagingSenderId: '570543922512',
    projectId: 'kostparkir',
    databaseURL:
        'https://kostparkir-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kostparkir.appspot.com',
    iosClientId:
        '570543922512-8q6p9abocp2kq7gkg5st5a66t97ab0r4.apps.googleusercontent.com',
    iosBundleId: 'com.kostparkir.kostparkir',
  );
}
